development:
  adapter: postgresql
  database: library-checkout-development
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: library-checkout-test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: library-checkout-production
  pool: 5
  timeout: 5000
